"""add phone number to user profiles

Revision ID: 4a0f45da4eec
Revises: c767857c4f17
Create Date: 2026-10-06 14:39:26.395523
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4a0f45da4eec'
down_revision: Union[str, Sequence[str], None] = 'c767857c4f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('phone_number', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'phone_number')
    # ### end Alembic commands ###