"""create project requests

Revision ID: 831012b71b14
Revises: 677082ff12bd
Create Date: 2026-09-04 21:11:27.494390
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '831012b71b14'
down_revision: Union[str, Sequence[str], None] = '677082ff12bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_requests_action'), 'project_requests', ['action'], unique=False)
    op.create_index(op.f('ix_project_requests_id'), 'project_requests', ['id'], unique=False)
    op.create_index(op.f('ix_project_requests_project_id'), 'project_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_requests_requested_by'), 'project_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_project_requests_status'), 'project_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_requests_status'), table_name='project_requests')
    op.drop_index(op.f('ix_project_requests_requested_by'), table_name='project_requests')
    op.drop_index(op.f('ix_project_requests_project_id'), table_name='project_requests')
    op.drop_index(op.f('ix_project_requests_id'), table_name='project_requests')
    op.drop_index(op.f('ix_project_requests_action'), table_name='project_requests')
    op.drop_table('project_requests')
    # ### end Alembic commands ###