"""add workspace requests

Revision ID: eca25453a18f
Revises: 1cd7d284ded0
Create Date: 2026-08-25 10:05:32.436831
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'eca25453a18f'
down_revision: Union[str, Sequence[str], None] = '1cd7d284ded0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_requests_id'), 'workspace_requests', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_requests_requested_by'), 'workspace_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_workspace_requests_status'), 'workspace_requests', ['status'], unique=False)
    op.create_index(op.f('ix_workspace_requests_workspace_id'), 'workspace_requests', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_requests_workspace_id'), table_name='workspace_requests')
    op.drop_index(op.f('ix_workspace_requests_status'), table_name='workspace_requests')
    op.drop_index(op.f('ix_workspace_requests_requested_by'), table_name='workspace_requests')
    op.drop_index(op.f('ix_workspace_requests_id'), table_name='workspace_requests')
    op.drop_table('workspace_requests')
    # ### end Alembic commands ###